# https://pre-commit.com/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    # Checker
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: name-tests-test
        args: [--pytest-test-first]
    # Formatter
    -   id: end-of-file-fixer
    -   id: pretty-format-json
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.8
      args: [wonderland]
      always_run: true
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [wonderland/udfs]
        always_run: true
-   repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        name: isort (python)
        args: [wonderland/udfs]
        always_run: true
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: poetry run pytest -s -v wonderland
        types: [python]
        pass_filenames: false
        always_run: true
    -   id: pytest-cov
        name: pytest-cov
        stages: [push]
        language: system
        entry: poetry run pytest -v --cov=ethosu --cov-fail-under=0
        types: [python]
        pass_filenames: false
        always_run: true
    -   id: poetry-lock
        name: poetry-lock
        stages: [commit]
        language: system
        entry: poetry lock
        types: [python]
        pass_filenames: false
        always_run: true
